## 16. Lambda in Python

Q. What is Lambda?

A `lambda function` is a small anonymous(unnamed) function.

syntax:

lambda arguments:expression

* No def keyword
* single expression only
* Return value automatically

## 2. What is map()?

map() applies a function to each item of an iterable(like list, tuple)

In [1]:
# user defined function 
def sumTwo(x,y):
    return x+y
    
sumTwo(10,12)

22

In [2]:
# anonymous function: function without name
(lambda x,y:x+y)(10,12)

22

In [3]:
sumTwo(10,45)

55

In [4]:
(lambda x,y:x+y)(10,45)

55

Syntax:

* Normal Function : lambda 
* Anonymous Function:
    >lambda with filter()
    
    >lambda with map()
    
    >lambda with reduce()
    
    >lambda with apply()
* CommonError
   > SyntaxError
   > TypeError

In [1]:
# user defined function
def addTwo(a,b):
    return a+b
addTwo(10,12)

22

In [2]:
# lambda function : anonymous function(function without theiir name, One line expression)
(lambda a,b:a+b)(10,12)

22

In [4]:
# using User input

def addTwo(x,y):
    sum1 = x+y
    return f"Sum of the two numbers {x} and {y} is {sum1}"

a = int(input("Enter first Number: "))
b = int(input("Enter second number"))
addTwo(a,b)

Enter first Number:  10
Enter second number 14

'Sum of the two numbers 10 and 14 is 24'

In [5]:
a = int(input("Enter first Number: "))
b = int(input("Enter second number"))

(lambda x,y:x+y)(a,b)

Enter first Number:  14
Enter second number 15

29

In [8]:
# lambda with filter()

list1 = [1,2,3,4,5,6,7,8,9,10]

for i in list1:
    # print(i)
    if i%2==0:
        print(i,end=" ")

2 4 6 8 10

In [11]:
for j in list1:
    # print(j)
    if j%2!=0:
        print(j,end=" ")

1 3 5 7 9

filter(func,sequence)

In [14]:
list1 = [1,2,3,4,5,6,7,8,9,10]

# Anonymous function
list(filter(lambda a:a%2==0,list1))  # object code

[2, 4, 6, 8, 10]

In [16]:
def findEven(x):
    if x%2==0:
        return x

findEven(11)

In [18]:
tuple(filter(findEven,list1))

(2, 4, 6, 8, 10)

In [22]:
# 2.lambda with map()

# map(func,sequence)

In [30]:
# lambda with map()
list1 = [1,2,3,4,5,6,7,8,9,10]
print('Original List:',list1)

# Normal Function

def sqrNum(x):
    return x**2

sqrNum(2)




# Anonymous function

Original List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

4

In [31]:
list(map(sqrNum,list1))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [33]:
# Anonymous function
list1 = [1,2,3,4,5,6,7,8,9,10]
list(map(lambda x1:x1**2,list1))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# lambda with reduce()

`readuce()` is used to apply a function to items of an iterable and reduce it to a single value.

`from functools import reduce`

#### syntax:

* reduce(function, iterable)
* applies function step-by-step
* return inside reduce

In [34]:
from functools import reduce

In [35]:
help(reduce)

Help on built-in function reduce in module _functools:

reduce(...)
    reduce(function, iterable[, initial], /) -> value

    Apply a function of two arguments cumulatively to the items of an iterable, from left to right.

    This effectively reduces the iterable to a single value.  If initial is present,
    it is placed before the items of the iterable in the calculation, and serves as
    a default when the iterable is empty.

    For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5])
    calculates ((((1 + 2) + 3) + 4) + 5).

syntax:
reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]

In [36]:
((((1 + 2) + 3) + 4) + 5)

15

In [37]:
list1=[1,2,3,4,5,6,7,8,9,10]

# normal function
def reduceValue(x,y):
    return x+y

In [38]:
# : reduce(lambda x, y: x+y, [1, 2, 3, 4, 5])

reduce(reduceValue,list1)

55

In [42]:
# Second method 

list1=[1,2,3,4,5,6,7,8,9,10]
reduce(lambda a,b:a/b, list1)

2.7557319223985894e-07

In [43]:
## lambda with apply()

In [44]:
import pandas as pd

In [46]:
listData = [1,2,3,4,5,6,7,8,9,10] # series 
print("My Series is:",listData)

df = pd.DataFrame(listData)
df

My Series is: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [52]:
dataList = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]  #3x4=12
print("Nested List:",dataList)

# convert list to dataFrame 
df1 = pd.DataFrame(dataList)
df1

Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [54]:
# lambda with apply 

# for i in df1:
#     print(i)

0
1
2

In [56]:
# syntax
# df1.apply(function)

In [57]:
# square of the value which is stored in dataframe
df2 = df1.apply(lambda a:a**2)
df2

     0    1    2
0    1    4    9
1   16   25   36
2   49   64   81
3  100  121  144